package UI;

import java.awt.CardLayout;
import Model.*;
import java.awt.Dimension;

/**
 *
 * @author lethi
 */
public class FormQuanLy extends javax.swing.JFrame {

    CardLayout cl;
    private NhanVien nv;
    String chucvu;

    public NhanVien getNv() {
        return nv;
    }

    public void setNv(NhanVien nv) {
        this.setTitle(nv.getTenNV());
        banHangJPanel1.setNv(nv);
        phieuChiPanel1.nv = nv;
        this.nv = nv;
        phanQuyen();
    }

    private void phanQuyen() {
        if (nv.getChucVu().equalsIgnoreCase("nhân viên")) {
            MenuPanel.add(btnBanHang);
            MenuPanel.add(btnKhachHang);
            MenuPanel.add(btnSanPham);
            sanPhamPanel1.setNv(nv);
            MenuPanel.add(btnPhieuChi);
            MenuPanel.add(btnDangXuat);
        }else{
            MenuPanel.add(btnBanHang);
            MenuPanel.add(btnSanPham);
            MenuPanel.add(btnNhanVien);
            MenuPanel.add(btnKhachHang);
            MenuPanel.add(btnPhieuChi);
            MenuPanel.add(btnThongKe);
            MenuPanel.add(btnDangXuat);
        }
    }

    /**
     * Creates new form FormQuanLy
     */
    public FormQuanLy() {
        initComponents();
        cl = (CardLayout) PanelMain.getLayout();
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBanHang = new javax.swing.JButton();
        btnPhieuChi = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        MenuPanel = new javax.swing.JPanel();
        btnPhieuChi1 = new javax.swing.JButton();
        PanelMain = new javax.swing.JPanel();
        banHangJPanel1 = new UI.BanHangJPanel();
        nhanVienPanel1 = new UI.NhanVienPanel();
        phieuChiPanel1 = new UI.PhieuChiPanel();
        thongKePanel1 = new UI.ThongKePanel();
        khachHangPanel11 = new UI.KhachHangPanel1();
        sanPhamPanel1 = new UI.SanPhamPanel();
        khuyenMaiJpanel1 = new UI.KhuyenMaiJpanel();

        btnBanHang.setBackground(new java.awt.Color(41, 41, 41));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart.png"))); // NOI18N
        btnBanHang.setText("Bán Hàng");
        btnBanHang.setBorder(null);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnPhieuChi.setBackground(new java.awt.Color(41, 41, 41));
        btnPhieuChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPhieuChi.setForeground(new java.awt.Color(255, 255, 255));
        btnPhieuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/truck.png"))); // NOI18N
        btnPhieuChi.setText("Phiếu chi");
        btnPhieuChi.setBorder(null);
        btnPhieuChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuChiActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(41, 41, 41));
        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N
        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.setBorder(null);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(41, 41, 41));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/employee.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setBorder(null);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(41, 41, 41));
        btnSanPham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pizza_icon.png"))); // NOI18N
        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setBorder(null);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(41, 41, 41));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reckon.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setBorder(null);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(41, 41, 41));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_out.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setBorder(null);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanel.setBackground(new java.awt.Color(41, 41, 41));
        MenuPanel.setPreferredSize(new java.awt.Dimension(160, 650));
        MenuPanel.setLayout(new java.awt.GridLayout(10, 1));

        btnPhieuChi1.setBackground(new java.awt.Color(41, 41, 41));
        btnPhieuChi1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPhieuChi1.setForeground(new java.awt.Color(255, 255, 255));
        btnPhieuChi1.setText("Khuyến mãi");
        btnPhieuChi1.setBorder(null);
        btnPhieuChi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuChi1ActionPerformed(evt);
            }
        });
        MenuPanel.add(btnPhieuChi1);

        PanelMain.setMinimumSize(new java.awt.Dimension(910, 650));
        PanelMain.setPreferredSize(new java.awt.Dimension(910, 650));
        PanelMain.setLayout(new java.awt.CardLayout());
        PanelMain.add(banHangJPanel1, "cardbanhang");
        PanelMain.add(nhanVienPanel1, "NhanVienCard");
        PanelMain.add(phieuChiPanel1, "PhieuChiCard");
        PanelMain.add(thongKePanel1, "thongkecard");
        PanelMain.add(khachHangPanel11, "KhachHangCard");
        PanelMain.add(sanPhamPanel1, "sanphamcard");
        PanelMain.add(khuyenMaiJpanel1, "khuyenmaicard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "cardbanhang");
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "KhachHangCard");
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "NhanVienCard");
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhieuChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuChiActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "PhieuChiCard");
    }//GEN-LAST:event_btnPhieuChiActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "thongkecard");
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "sanphamcard");
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnPhieuChi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuChi1ActionPerformed
        // TODO add your handling code here:
        cl.show(PanelMain, "khuyenmaicard");
    }//GEN-LAST:event_btnPhieuChi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PanelMain;
    private UI.BanHangJPanel banHangJPanel1;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuChi;
    private javax.swing.JButton btnPhieuChi1;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKe;
    private UI.KhachHangPanel1 khachHangPanel11;
    private UI.KhuyenMaiJpanel khuyenMaiJpanel1;
    private UI.NhanVienPanel nhanVienPanel1;
    private UI.PhieuChiPanel phieuChiPanel1;
    private UI.SanPhamPanel sanPhamPanel1;
    private UI.ThongKePanel thongKePanel1;
    // End of variables declaration//GEN-END:variables
}
