/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.HoaDonCTDAO;
import DAO.HoaDonDAO;
import DAO.KhachHangDAO;
import DeskHelp.Decimal;
import DeskHelp.SalesInvoice;
import Model.HoaDon;
import Model.HoaDonCT;
import Model.KhachHang;
import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;
import java.util.ArrayList;

/**
 *
 * @author lethi
 */
public class HoaDonJframe extends javax.swing.JFrame {
     static GioHangJPanel giohang = new GioHangJPanel();
    static HoaDon hd = new HoaDon();
    static ArrayList<HoaDonCT> ds = new ArrayList<>();

    /**
     * Creates new form NewJFrame
     */
    public HoaDonJframe() {
        initComponents();
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    void setHoaDon(ArrayList<HoaDonCT> ds, Model.HoaDon hd, double total, double diem) {
        this.ds = ds;
        this.hd = hd;
        setTitle(this.hd.getId());
        hoadonjpanel.TaoDon(ds, hd, total, diem);
    }
    
    public static void CheckInt(int i) {
        // HOADON-HOADONCT-SANPHAM-KHACHHANG
        if (i == 1) {
            //Check điểm tích lũy rước
            int diem = hd.getThanhTien()
                    .multiply(BigDecimal.valueOf(0.1))
                    .divide(Decimal.COnvertIntToBigDecimal(1000))
                    .intValue();
            hd.setDiemTichLuy(diem);

            int checkHdInsert = new HoaDonDAO().InsertSQL(hd);
            if (checkHdInsert == 1) {
                if (hd.getIdKhachHang() != -1) {
                    KhachHang kh = new KhachHangDAO().getObjectById(String.valueOf(hd.getIdKhachHang()));
                    int diemht = kh.getDiemTichLuy();
                    kh.setDiemTichLuy(diemht + diem);
                    new KhachHangDAO().UpdateSQL(kh);
                }
                new HoaDonCTDAO().InsertSQL(ds);
            }
            giohang.reset();
            
            JOptionPane.showMessageDialog(null, "Đã tạo hóa đơn thành công");
        } else {
            new BanHangJPanel().resetUI();
            JOptionPane.showMessageDialog(null, "Chưa tạo hóa đơn");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        hoadonjpanel = new UI.HoadonJpanel();
        jButton1 = new javax.swing.JButton();
        txtTienTra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 600));

        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hoadonjpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hoadonjpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("In hoa don");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTienTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienTraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienTraKeyReleased(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tiền khách trả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!txtTienTra.getText().isEmpty()) {
            if (hoadonjpanel.checkTienKhachTra() == 1) {
                new SalesInvoice().printInvoice(hoadonjpanel, hoadonjpanel.getWidth() + 100, hoadonjpanel.getHeight());
            } else {
                JOptionPane.showMessageDialog(this, "Khách chưa trả đủ tiền");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa nhập tiền khách trả");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTienTraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienTraKeyReleased
        // TODO add your handling code here:
        if (txtTienTra.getText().matches("[0-9]+")) {
            if (Character.isDigit(evt.getKeyChar())) {
                if (!txtTienTra.getText().isEmpty()) {
                    hoadonjpanel.settienthoi(Double.parseDouble(txtTienTra.getText()));
                } else {
                    hoadonjpanel.settienthoi(0);
                }
            }
        }
    }//GEN-LAST:event_txtTienTraKeyReleased

    private void txtTienTraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienTraKeyPressed
        // TODO add your handling code here:
//        char x = evt.getKeyChar();
//        if(Character.isDigit(x)&&Character.compare(x, '\\b"))){
//            txtTienTra.setEditable(false);
//        }else{
//            txtTienTra.setEditable(true);
//        }
    }//GEN-LAST:event_txtTienTraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UI.HoadonJpanel hoadonjpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTienTra;
    // End of variables declaration//GEN-END:variables
}
