/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.ChuongTrinhKMDAO;
import DAO.MaKhuyenMaiDAO;
import Model.ChuongTrinhKM;
import Model.MaKhuyenMai;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lethi
 */
public class KhuyenMaiJpanel extends javax.swing.JPanel {
    DefaultTableModel modelCT,modelCode;
    ArrayList<ChuongTrinhKM> dsCT = new ArrayList<>();
    ArrayList<MaKhuyenMai> dsCode = new ArrayList<>();
    /**
     * Creates new form KhuyenMaiJpanel
     */
    public KhuyenMaiJpanel() {
        initComponents();
        modelCT = (DefaultTableModel) tblkhuyenmai.getModel();
        modelCode = (DefaultTableModel) tblcode.getModel();
        
        LoadDataCT();
        
    }
    
    void LoadDataCT(){
        dsCT = new ChuongTrinhKMDAO().getArrayListAll();
        modelCT.setRowCount(0);
        for (ChuongTrinhKM ct : dsCT){
            modelCT.addRow(new Object[]{ct.getId(),ct.getTenCT(),ct.getMoTa(),ct.getPhanTramGiam(),ct.getNgayBatDau(),ct.getNgayKetThuc()});
        }
    }
    void LoadDataCode(ArrayList<MaKhuyenMai> dscode){
        LocalDate ngayketthucCT =new ChuongTrinhKMDAO().getObjectById(tblkhuyenmai.getValueAt(tblkhuyenmai.getSelectedRow(), 0).toString()).getNgayKetThuc();
        LocalDate ngayhientai =  LocalDate.now();
        tblkhuyenmai.getValueAt(tblkhuyenmai.getSelectedRow(), 5);
        modelCode.setRowCount(0);
        for(MaKhuyenMai ma : dscode){
            LocalDate ngaysudung= ma.getNgaySuDung();
            
            if(ngayketthucCT.isBefore(ngayhientai)&& ngaysudung==null){
                modelCode.addRow(new Object[]{ma.getCode(),"Hết hạn"});
            }
            else if(ngaysudung ==null){
                modelCode.addRow(new Object[]{ma.getCode(),"Chưa dùng"});
            }else{
                modelCode.addRow(new Object[]{ma.getCode(),ngaysudung});
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblkhuyenmai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblcode = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(910, 650));

        tblkhuyenmai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "TÊN CT", "MÔ TẢ", "GIẢM GIÁ", "NGÀY BẮT ĐẦU", "NGÀY KẾT THÚC"
            }
        ));
        tblkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblkhuyenmaiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblkhuyenmai);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KHUYẾN MÃI");

        jButton1.setText("THÊM CT KHUYỄN MÃI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("THÊM MÃ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("KẾT THÚC CT SỚM");

        tblcode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODE KHUYẾN MÃI", "NGÀY SỬ DỤNG"
            }
        ));
        jScrollPane2.setViewportView(tblcode);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 418, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblkhuyenmaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhuyenmaiMousePressed
        // TODO add your handling code here:
        
        LoadDataCode(new MaKhuyenMaiDAO().getArrayListByCTKM(tblkhuyenmai.getValueAt(tblkhuyenmai.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_tblkhuyenmaiMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TaoMaKhuyenMaiJFrame tao = new TaoMaKhuyenMaiJFrame();
        tao.ParentJpaner=this;
        tao.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String soluong  = JOptionPane.showInputDialog(this, "Tạo thêm code cho Chương trình Khuyến Mãi:\n"+tblkhuyenmai.getValueAt(tblkhuyenmai.getSelectedRow(), 1));
        if(soluong!=null||soluong !=""){
            new MaKhuyenMaiDAO().InsertSQL(tblkhuyenmai.getValueAt(tblkhuyenmai.getSelectedRow(),0).toString(), Integer.parseInt(soluong));
            LoadDataCode(new MaKhuyenMaiDAO().getArrayListByCTKM(tblkhuyenmai.getValueAt(tblkhuyenmai.getSelectedRow(),0).toString()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblcode;
    private javax.swing.JTable tblkhuyenmai;
    // End of variables declaration//GEN-END:variables
}
